# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airbyte-custom-connector
  namespace: airbyte
  labels:
    app: airbyte-custom-connector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airbyte-custom-connector
  template:
    metadata:
      labels:
        app: airbyte-custom-connector
    spec:
      containers:
        - name: connector
          image: abduljabbaracrirmaiairbyte.azurecr.io/airbyte-custom-connector:v1
          imagePullPolicy: Always
          volumeMounts:
            - name: data-volume
              mountPath: /app/data
          env:
            - name: AZURE_OPENAI_KEY
              valueFrom:
                secretKeyRef:
                  name: openai-secret
                  key: AZURE_OPENAI_KEY
      volumes:
        - name: data-volume
          emptyDir: {}




