name: Build and Push to ACR

on:
  push:
    branches:
      - main  # or change this to your branch name

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Azure Container Registry
      uses: docker/login-action@v2
      with:
        registry: ${{ secrets.ACR_LOGIN_SERVER }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build the Docker image
      run: |
        docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/myapp:latest .

    - name: Push the Docker image
      run: |
        docker push ${{ secrets.ACR_LOGIN_SERVER }}/myapp:latest
